### ISSUE TITLE
Consolidate common CRUD logic for ngrok API 

### ISSUE THREAD

**Issue by jonstacks** [ngrok/kubernetes-ingress-controller#118]
### Description

Common logic has emerged across various controllers and ngrok API objects to make sure the API matches what is in the Spec for the resources. The reconciliation for this looks something like:

```
DELETE_FLOW:
    If we don't have an ID,
        Do nothing and return
    If we do have an ID,
        Try to Delete it
            If there was no error, return
            If the error is a 404 not found, its already been deleted, so don't return an error
            Return the error 

CREATE_OR_UPDATE_FLOW:
    CREATE_FLOW:
        If we can search and find a matching object, search for the object
            If we find an object
                Use it and return it and store the ID in a status field
        Create the object in the API and store the ID in a status field
 
    If we don't have an ID
        CREATE_FLOW
    If we do have an ID
        Check that it exists in the ngrok API
            If it does not exist
                 CREATE_FLOW
        Update the API to match the spec.
```

Consolidate this logic into a single place

### Use Case

Currently we duplicate a lot of the logic for this flow between many controllers and across quite a few ngrok API resources. We should put this flow logic into a single place to make it easier to maintain.

**Comment by alex-bezek** [comment]
Closing this as @nikolay-ngrok completed this with the base controller.
