### ISSUE TITLE
Docs: Oauth

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/kubernetes-ingress-controller#182]
### Description

Oauth is one of our most useful route module configurations that is commonly used to showcase the power you can add by putting ngrok in front of services. It deserves its own specific example and doc page

### Use Case

This is a very common and useful endpoint configuration we point people to

**Comment by sudobinbash** [comment]
should we close this @alex-bezek ?

**Comment by alex-bezek** [comment]
@sudobinbash I was originally thinking of making a doc for oauth specifically here https://github.com/ngrok/kubernetes-ingress-controller/blob/main/docs/examples/oauth/README.md since its such a popular route module. https://ngrok.com/docs/using-ngrok-with/k8s/ that you made does cover basic oauth usage though. 

If you think that is good for now I can update this file to point to that and the moduleset doc page
