### ISSUE TITLE
Add an icon to the ngrok helm chart

### ISSUE THREAD

**Issue by sudobinbash** [ngrok/kubernetes-ingress-controller#245]
### Description

Add an icon to the ngrok ingress controller helm chart.
Docs: https://helm.sh/docs/topics/charts/

**Why:** It makes the ingress controller look great when imported on managed kubernetes solutions like Rafay, EKS, and Vultr

**Comment by jonstacks** [comment]
Fixed in https://github.com/ngrok/kubernetes-ingress-controller/pull/252
