### ISSUE TITLE
Issue templates for bugs should prompt for additional information. 

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/kubernetes-ingress-controller#284]
Now that we have launched we've gotten some great and much needed feedback. When people submit issues for bugs, it would be very helpful to have some additional context like their k8s version, helm chart version, values they override, etc. 

It would help us if this context was provided in bug support tickets we get. We can request this information easily via issue templates.

**Comment by CK-Ward** [comment]
Hey @alex-bezek, thanks for making this issue! Agreed that having this info upfront would help us narrow our triaging more effectively. 

Before I assign this to a team member to create, based on your experience triaging issues for the ingress controller, can I get a list of what you think you think would be helpful? So far, I see 

- k8s version
- helm chart version
- overridden values

Perhaps we can add:
- ingress controller version 

Anything else?

**Comment by alex-bezek** [comment]
I think that covers the major things. Perhaps k8s distribution (minikube, eks, etc) would be useful as well. I think we can start here and always add things if we find more info we wish we had on logged issues

**Comment by CK-Ward** [comment]
@ofthedelmer
