### ISSUE TITLE
Container ngrok-ingress-controller failed liveness probe

### ISSUE THREAD

**Issue by Mehonoshin** [ngrok/kubernetes-ingress-controller#289]
### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4-rc3+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-25T22:00:15Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Helm Chart Version

0.10.0

### Helm Chart configuration

Nothing, just `credentials.apiKey` and `credentials.authtoken`

### What happened

Hey folks, and thank you for publishing this chart!
I followed steps described in docs on a fresh k3s cluster.
As the result the ngrok-ingress-controller pod didn't start at all.

Here is the output of `kubectl describe pod ngrok-kubernetes-ingress-controller-manager-55b4b7f998-42tqr`
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  24m                   default-scheduler  Successfully assigned ngrok-ingress-controller/ngrok-kubernetes-ingress-controller-manager-55b4b7f998-42tqr to node3
  Normal   Pulled     23m (x2 over 24m)     kubelet            Container image "docker.io/ngrok/kubernetes-ingress-controller:0.8.0" already present on machine
  Normal   Created    23m (x2 over 24m)     kubelet            Created container ngrok-ingress-controller
  Normal   Killing    23m                   kubelet            Container ngrok-ingress-controller failed liveness probe, will be restarted
  Warning  Unhealthy  23m                   kubelet            Readiness probe failed: Get "http://10.42.2.5:8081/readyz": read tcp 10.42.2.1:53944->10.42.2.5:8081: read: connection reset by peer
  Normal   Started    23m (x2 over 24m)     kubelet            Started container ngrok-ingress-controller
  Warning  Unhealthy  22m (x11 over 24m)    kubelet            Readiness probe failed: Get "http://10.42.2.5:8081/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  19m (x15 over 24m)    kubelet            Liveness probe failed: Get "http://10.42.2.5:8081/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  9m44s (x2 over 15m)   kubelet            (combined from similar events): Readiness probe failed: Get "http://10.42.2.5:8081/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    4m34s (x50 over 18m)  kubelet            Back-off restarting failed container ngrok-ingress-controller in pod ngrok-kubernetes-ingress-controller-manager-55b4b7f998-42tqr_ngrok-ingress-controller(2cd5f78f-940d-4453-8647-d43ba3692292)
```

What is the best way for troubleshooting the issue?

**Comment by Wonderful-Space** [comment]
Hey there @Mehonoshin! Thanks for taking the time to make an issue to report this.

Would you be able to send us some additional debug information? Do you see anything suspicious in the pod logs for the ingress controller (`kubectl logs ngrok-kubernetes-ingress-controller-manager-55b4b7f998-42tqr`)? Have you tried doing a full teardown and starting from scratch again?

**Comment by Mehonoshin** [comment]
Sorry for bothering, the issue was not related to the chart itself, but misconfiguration of Flannel on my k3s cluster.
