### ISSUE TITLE
Support container lifecycle hooks

### ISSUE THREAD

**Issue by basilnsage** [ngrok/kubernetes-ingress-controller#299]
### Description

Hello,

Please expose a config option to allow users to customize the ingress controller container's [lifecycle hooks](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1). Happy to raise a PR if this request sounds reasonable.

Thanks, 

### Use Case

I have custom cleanup actions that I need to perform before stopping the controller container. Currently, the Helm chart doesn't support methods to trigger these custom actions, and I'd prefer not to go through the effort of creating a mutating webhook just for this.

**Comment by nikolay-ngrok** [comment]
Hello @basilnsage,

We're happy to look over a PR that covers your thinking/needs.

Meanwhile, I'll be looking at the documentation and experiment to confirm if we want to support this for the ingress controller. From the documentation, it seems like you might need exec style of webhook, is this correct?
