### ISSUE TITLE
Update https://ngrok.github.io/kubernetes-ingress-controller/

### ISSUE THREAD

**Issue by russorat** [ngrok/kubernetes-ingress-controller#308]
### Kubernetes Version

latest

### Helm Chart Version

latest

### What happened

The page hosted at https://ngrok.github.io/kubernetes-ingress-controller/ is in need of some updates. I can see the following:

- Ngrok should be ngrok
- We are out of Alpha status
- We should link to the documentation instead of under contruction
- remove the bit about configuring the agent

**Comment by CK-Ward** [comment]
@russorat is this still applicable? looks like the work here is done

**Comment by russorat** [comment]
looks pretty good! i still see broken images at the top of the page: 
![image](https://github.com/ngrok/kubernetes-ingress-controller/assets/4805997/b432980b-fdf6-4f61-ba37-e66e2f477b21)

**Comment by russorat** [comment]
it looks like these images are still broken

**Comment by bobzilladev** [comment]
Should be fixed next release, due to https://github.com/ngrok/kubernetes-ingress-controller/pull/333

**Comment by alex-bezek** [comment]
![image](https://github.com/ngrok/kubernetes-ingress-controller/assets/8029578/51f56b42-2535-4639-a320-2655dbbff0c3)
This does still seem to be an issue

**Comment by bobzilladev** [comment]
Ah, the [artifacthub](https://artifacthub.io/packages/helm/ngrok/kubernetes-ingress-controller) logo is fixed (and i was able to get us "verified" and "official" there, as well as removing the old version with the different project name). But the link in the readme isn't updated.

**Comment by bobzilladev** [comment]
Ah, gh-pages is missing the current `docs/assets/`, pr to fix: https://github.com/ngrok/kubernetes-ingress-controller/pull/348

**Comment by jonstacks** [comment]
@russorat, I've update https://ngrok.github.io/kubernetes-ingress-controller/ with the latest `README.md` from `main`, can you let me know what you think?

**Comment by russorat** [comment]
amazing! thank you!
