### ISSUE TITLE
Allow the ingress controller to successfully deploy without authtoken or apikey's defined

### ISSUE THREAD

**Issue by russorat** [ngrok/kubernetes-ingress-controller#317]
### Description

Many of the k8s marketplaces we are trying to get listed in have a '1 click install' process which runs the helm install with default values and then allows us to give instructions to configure it after the fact. 

currently, trying to install our ingress controller without an authtoken or apikey fails to start the pod and as such, the 1-click install also fails in the marketplaces. I understand you can't do anything without the authtoken and apikey, but the ability to provide it later via a helm or kubectl command would allow us to get into these marketplaces.

so the ask: can we allow the ingress controller to be installed successfully and add the secrets later? The ingress controller shouldn't "work" without the keys, but the pods need to not crash so that it can pass the 1-click install tests for the marketplaces.

**Comment by bobzilladev** [comment]
Could likely set the secrets to be optional (i had to do that in tunnel.v2/handler recently for cookie migration). The pod will then start, and can handle the missing secrets up in the code, guard against trying to do anything. Probably have to listen for k8s update events so it populates in memory after the secrets are finally set.

**Comment by Abdiramen** [comment]
So, here's where we are:
- Optional secrets ✅ 
- throw error without crash-looping ❌ (working on this portion now)
- wait for key to be provided ❓ (we might already have this)

**Comment by Abdiramen** [comment]
changes made here: https://github.com/digitalocean/marketplace-kubernetes/pull/492
