### ISSUE TITLE
Support Multiple Rules per ingress

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/kubernetes-ingress-controller#56]
Currently we only support 1 rule per ingress as a shortcut during our initial development phase. We should support multiple rules

**Comment by jonstacks** [comment]
While we are doing this, I'm going to look at supporting multiple rules per ingress as well as multiple rules for the same host defined in multiple ingresses.

**Comment by jonstacks** [comment]
We are going to wait until we implement a store. This will be much easier after that

**Comment by alex-bezek** [comment]
This functionality was handled as a part of the store https://github.com/ngrok/kubernetes-ingress-controller/issues/93
